import type { AccountWorkspaceFilters } from "@/features/accounts/types/account-workspace"
import { useTranslation } from "@/i18n/useTranslation"

type Update = <Key extends keyof AccountWorkspaceFilters>(key: Key, value: AccountWorkspaceFilters[Key]) => void
export function AccountFilterBar({ filters, currencies, resultCount, onChange }: { filters: AccountWorkspaceFilters; currencies: string[]; resultCount: number; onChange: Update }) {
  const { t } = useTranslation()
  const input = "h-10 rounded-lg border border-[var(--border-subtle)] bg-background px-3 text-sm focus-visible:ring-2"
  return <div className="mt-6 grid gap-3 border-y border-[var(--border-subtle)] py-4 sm:grid-cols-2 lg:grid-cols-[minmax(14rem,1fr)_repeat(2,auto)_auto]"><input aria-label={t("accounts.workspace.search")} placeholder={t("accounts.workspace.searchPlaceholder")} value={filters.search} onChange={(event) => onChange("search", event.target.value)} className={input} /><select aria-label={t("accounts.workspace.filterCurrency")} value={filters.currency ?? ""} onChange={(event) => onChange("currency", event.target.value || null)} className={input}><option value="">{t("assets.filters.allCurrencies")}</option>{currencies.map((item) => <option key={item}>{item}</option>)}</select><select aria-label={t("accounts.workspace.filterStatus")} value={filters.lifecycle} onChange={(event) => onChange("lifecycle", event.target.value as AccountWorkspaceFilters["lifecycle"])} className={input}><option value="all">{t("assets.workspace.allStatuses")}</option><option value="active">{t("assets.card.active")}</option><option value="archived">{t("assets.card.archived")}</option></select><span className="self-center text-xs text-muted-foreground">{t("accounts.workspace.results", { count: resultCount })}</span></div>
}
