import { AlertTriangle, CheckCircle2, CircleOff } from "lucide-react"
import type { AccountAnalyticalSnapshot, AccountHealthFactorId } from "@/features/accounts/types/account-workspace"
import { useTranslation } from "@/i18n/useTranslation"

export function AccountHealth({ analysis, selected, onSelect }: { analysis: AccountAnalyticalSnapshot; selected: AccountHealthFactorId | null; onSelect: (id: AccountHealthFactorId | null) => void }) {
  const { t } = useTranslation()
  const detail = analysis.factors.find((factor) => factor.id === selected)
  return <section aria-labelledby="account-health-title" className="mt-14 border-t border-[var(--border-subtle)] pt-9">
    <header className="tharwati-section-header"><p className="tharwati-eyebrow">{t("accounts.health.eyebrow")}</p><h2 id="account-health-title" className="tharwati-section-title mt-2">{t("accounts.health.title")}</h2><p className="tharwati-section-description">{t("accounts.health.description")}</p></header>
    <div className="mt-7 grid gap-8 lg:grid-cols-[15rem_minmax(0,1fr)]"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">{t("accounts.health.overall")}</p><p className="mt-3 font-heading text-5xl tabular-nums">{analysis.overallScore === null ? "—" : `${analysis.overallScore}%`}</p><p className="mt-3 text-sm text-muted-foreground">{analysis.provisional ? t("accounts.health.provisional") : t("accounts.health.complete")}</p></div>
      <div className="divide-y divide-[var(--border-subtle)] border-y border-[var(--border-subtle)]">{analysis.factors.map((factor) => { const Icon = factor.availability === "unavailable" ? CircleOff : factor.affectedAccountIds.length ? AlertTriangle : CheckCircle2; return <button key={factor.id} type="button" aria-pressed={selected === factor.id} onClick={() => onSelect(selected === factor.id ? null : factor.id)} className="grid w-full grid-cols-[1fr_auto] gap-4 px-2 py-4 text-start outline-none transition-colors hover:bg-muted/30 focus-visible:ring-2 aria-pressed:bg-muted/50 motion-reduce:transition-none"><span className="flex gap-3"><Icon size={17} aria-hidden="true" className="mt-0.5 text-muted-foreground"/><span><strong className="block text-sm">{t(`accounts.health.factor.${factor.id}`)}</strong><span className="mt-1 block text-xs text-muted-foreground">{factor.availability === "unavailable" ? t("accounts.health.unavailable") : t("accounts.health.coverage", { numerator: factor.numerator, denominator: factor.denominator })}</span></span></span><span className="tabular-nums text-sm font-semibold">{factor.score === null ? "—" : `${factor.score}%`}</span></button> })}</div>
    </div>{detail ? <div role="status" className="mt-5 border-s-2 border-primary ps-4 text-sm text-muted-foreground"><strong className="block text-foreground">{t(`accounts.health.factor.${detail.id}`)}</strong><p className="mt-1">{detail.explanation}</p></div> : null}
  </section>
}
