import { AlertTriangle, CircleCheck } from "lucide-react"
import type { AccountAnalyticalSnapshot, AccountInventoryItem, AccountQualityIssueId } from "@/features/accounts/types/account-workspace"
import { useTranslation } from "@/i18n/useTranslation"

export function AccountDataQuality({ analysis, items, selected, onSelect }: { analysis: AccountAnalyticalSnapshot; items: AccountInventoryItem[]; selected: AccountQualityIssueId | null; onSelect: (id: AccountQualityIssueId | null) => void }) {
  const { t } = useTranslation(); const issue = analysis.issues.find((entry) => entry.id === selected); const affected = issue ? items.filter((item) => issue.affectedAccountIds.includes(item.account.id)) : []
  return <section aria-labelledby="account-quality-title" className="mt-14 border-t border-[var(--border-subtle)] pt-9"><header className="tharwati-section-header"><p className="tharwati-eyebrow">{t("accounts.quality.eyebrow")}</p><h2 id="account-quality-title" tabIndex={-1} className="tharwati-section-title mt-2 outline-none">{t("accounts.quality.title")}</h2><p className="tharwati-section-description">{t("accounts.quality.description")}</p></header>
    {!analysis.issues.length ? <div className="mt-7 flex gap-3 border-y border-[var(--border-subtle)] py-6 text-sm"><CircleCheck size={18}/>{t("accounts.quality.empty")}</div> : <div className="mt-7 grid gap-8 lg:grid-cols-2"><div className="divide-y divide-[var(--border-subtle)] border-y border-[var(--border-subtle)]">{analysis.issues.map((entry) => <button key={entry.id} type="button" aria-pressed={selected === entry.id} onClick={() => onSelect(selected === entry.id ? null : entry.id)} className="flex w-full justify-between gap-4 px-2 py-4 text-start hover:bg-muted/30 focus-visible:ring-2 aria-pressed:bg-muted/50"><span className="inline-flex items-center gap-2 text-sm font-semibold"><AlertTriangle size={15} aria-hidden="true"/>{t(`accounts.quality.issue.${entry.id}`)}</span><span className="tabular-nums text-sm text-muted-foreground">{entry.count}</span></button>)}</div><div aria-live="polite">{issue ? <><h3 className="font-semibold">{t(`accounts.quality.issue.${issue.id}`)}</h3><p className="mt-2 text-sm text-muted-foreground">{t(`accounts.quality.explanation.${issue.id}`)}</p><ul className="mt-4 divide-y divide-[var(--border-subtle)] border-y border-[var(--border-subtle)]">{affected.map((item) => <li key={item.account.id} className="py-3 text-sm"><strong>{item.account.name}</strong><span className="ms-2 text-xs text-muted-foreground">{item.account.currency_code}</span></li>)}</ul></> : <p className="text-sm text-muted-foreground">{t("accounts.quality.selectPrompt")}</p>}</div></div>}
  </section>
}
