import type { AccountActivityEvidence, AccountActivityFilters } from "@/features/accounts/types/account-workspace"
import { formatPortfolioAmount } from "@/features/portfolio/utils/portfolio-formatters"
import { useTranslation } from "@/i18n/useTranslation"

export function AccountActivity({ activity, filters, types, error, onFilter, onOpen }: { activity: AccountActivityEvidence[]; filters: AccountActivityFilters; types: string[]; error: string | null; onFilter: (filters: AccountActivityFilters) => void; onOpen: (id: string) => void }) {
  const { t, language } = useTranslation(); const locale = language === "ar" ? "ar-SA" : "en-US"; const date = new Intl.DateTimeFormat(locale, { dateStyle: "medium" })
  return <section aria-labelledby="account-activity-title" className="mt-14 border-t border-[var(--border-subtle)] pt-9"><div className="flex flex-wrap items-end justify-between gap-4"><header><p className="tharwati-eyebrow">{t("accounts.activity.eyebrow")}</p><h2 id="account-activity-title" className="tharwati-section-title mt-2">{t("accounts.activity.title")}</h2><p className="tharwati-section-description">{t("accounts.activity.description")}</p></header><select aria-label={t("accounts.activity.filterType")} value={filters.transactionType ?? ""} onChange={(event) => onFilter({ transactionType: event.target.value || null })} className="h-10 border border-[var(--border-subtle)] bg-background px-3 text-sm"><option value="">{t("accounts.activity.allTypes")}</option>{types.map((type) => <option key={type} value={type}>{type}</option>)}</select></div>
    {error ? <p role="alert" className="mt-6 border-y border-red-500/30 py-6 text-sm text-red-700 dark:text-red-300">{error}</p> : activity.length ? <ol className="mt-5 divide-y divide-[var(--border-subtle)]">{activity.map((item) => <li key={item.transactionId}><button type="button" onClick={() => onOpen(item.transactionId)} className="grid w-full gap-2 py-4 text-start focus-visible:ring-2 sm:grid-cols-[auto_1fr_auto] sm:items-center sm:gap-4"><time dateTime={item.postedAt} className="text-xs text-muted-foreground">{date.format(new Date(item.postedAt))}</time><span className="min-w-0"><strong className="block truncate">{item.description}</strong><span className="mt-1 block text-xs text-muted-foreground">{item.type} · {t("portfolio.activity.posted")} · <span dir="ltr">{item.originalCurrency}</span></span></span><span dir="ltr" className="tabular-nums">{item.entries.length === 1 ? formatPortfolioAmount(item.entries[0].accountAmount, item.entries[0].accountCurrency, locale) : t("accounts.activity.multipleEntries", { count: item.entries.length })}</span></button></li>)}</ol> : <p className="mt-6 border-y border-[var(--border-subtle)] py-7 text-sm text-muted-foreground">{t("accounts.activity.empty")}</p>}
  </section>
}
