import { Dialog } from "@base-ui/react/dialog"
import { useEffect, useMemo, useState } from "react"
import { Button } from "@/components/ui/button"
import { assetsRepository } from "@/features/assets/repositories/assets.repository"
import { addBrokerageCashDividend } from "@/features/investments/repositories/brokerage-dividends.repository"
import { getBrokerageDividendPreview } from "@/features/investments/services/brokerage-dividend.service"
import { useTranslation } from "@/i18n/useTranslation"
import { localDateTimeInputToIso, formatLocalDateTimeInput } from "@/lib/formatting/local-date-time"
import type { AccountSummary, AssetSummary } from "@/lib/supabase/types"
import { compareDecimals } from "@/lib/financial-calculations/decimal"

const fieldClass="mt-1 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm"
const valid=(v:string)=>/^\d+(?:\.\d+)?$/.test(v.trim())
export function BrokerageDividendDialog({account,onClose,onSaved}:{account:AccountSummary|null;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const {t,language}=useTranslation(); const locale=language==="ar"?"ar-SA":"en-US"; const [assets,setAssets]=useState<AssetSummary[]>([]); const [assetId,setAssetId]=useState(""); const [gross,setGross]=useState(""); const [tax,setTax]=useState("0"); const [fees,setFees]=useState("0"); const [occurredAt,setOccurredAt]=useState(formatLocalDateTimeInput()); const [notes,setNotes]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null)
 useEffect(()=>{ if(account) void assetsRepository.searchAssets("",100).then(setAssets).catch(()=>setAssets([])) },[account])
 const asset=useMemo(()=>assets.find(a=>a.id===assetId)??null,[assets,assetId]); const preview=getBrokerageDividendPreview(gross,tax,fees); const same=!!asset&&asset.currency_code===account?.currency_code; const canSave=!!account&&!!asset&&same&&valid(gross)&&valid(tax)&&valid(fees)&&preview.net!==null&&compareDecimals(preview.net,"0")===1&&!!occurredAt
 const amount=(value:string|null)=>value===null?"--":new Intl.NumberFormat(locale,{style:"currency",currency:account?.currency_code??"USD",maximumFractionDigits:2}).format(Number(value))
 async function save(){if(!account||!asset||!canSave)return;setSaving(true);setError(null);try{await addBrokerageCashDividend({p_account_id:account.id,p_asset_id:asset.id,p_gross_dividend:gross,p_withholding_tax:tax,p_fees:fees,p_occurred_at:localDateTimeInputToIso(occurredAt),p_notes:notes.trim()||null});await onSaved()}catch(e){setError(e instanceof Error?e.message:t("brokerage.dividendError"))}finally{setSaving(false)}}
 return <Dialog.Root open={account!==null} onOpenChange={o=>!o&&!saving&&onClose()}><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 z-50 bg-black/40"/><Dialog.Popup className="fixed inset-x-3 top-1/2 z-50 mx-auto max-h-[90vh] max-w-lg -translate-y-1/2 overflow-y-auto rounded-xl bg-background p-5 shadow-xl sm:inset-x-0"><Dialog.Title className="font-heading text-xl">{t("brokerage.dividend")}</Dialog.Title><div className="mt-5 space-y-4"><label>{t("investment.asset.section")}<select className={fieldClass} value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">{t("investment.common.choose")}</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name}{a.symbol?` (${a.symbol})`:""}</option>)}</select></label>{asset&&!same?<p className="text-sm text-destructive">{t("brokerage.dividendCrossCurrencyUnsupported")}</p>:null}<label>{t("brokerage.grossDividend")}<input className={fieldClass} inputMode="decimal" value={gross} onChange={e=>setGross(e.target.value)}/></label><div className="grid gap-4 sm:grid-cols-2"><label>{t("brokerage.withholdingTax")}<input className={fieldClass} inputMode="decimal" value={tax} onChange={e=>setTax(e.target.value)}/></label><label>{t("investment.fees")}<input className={fieldClass} inputMode="decimal" value={fees} onChange={e=>setFees(e.target.value)}/></label></div><div className="rounded-lg bg-muted/50 p-3 text-sm"><span className="text-muted-foreground">{t("brokerage.netDividend")}</span><strong className="block tabular-nums">{amount(preview.net)}</strong></div><label>{t("investment.date")}<input className={fieldClass} type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label><label>{t("investment.notes")}<textarea className={fieldClass} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error?<p className="text-sm text-red-600">{error}</p>:null}<Button className="w-full" disabled={!canSave||saving} onClick={()=>void save()}>{saving?t("brokerage.savingDividend"):t("brokerage.dividend")}</Button></div></Dialog.Popup></Dialog.Portal></Dialog.Root>
}
