-- Restore the system category catalog after accidental remote cleanup.
-- Definitions intentionally match 20260820010000_add_record_categories.sql.

insert into public.record_categories (system_code, level, name, sort_order)
values
  ('food_drinks', 'main', 'Food & Drinks', 1),
  ('shopping', 'main', 'Shopping', 2),
  ('housing', 'main', 'Housing', 3),
  ('transportation', 'main', 'Transportation', 4),
  ('travel', 'main', 'Travel', 5),
  ('vehicle', 'main', 'Vehicle', 6),
  ('healthcare', 'main', 'Healthcare', 7),
  ('education', 'main', 'Education', 8),
  ('life_entertainment', 'main', 'Life & Entertainment', 9),
  ('communication', 'main', 'Communication', 10),
  ('subscriptions', 'main', 'Subscriptions', 11),
  ('family_children', 'main', 'Family & Children', 12),
  ('financial_expenses', 'main', 'Financial Expenses', 13),
  ('investments', 'main', 'Investments', 14),
  ('income', 'main', 'Income', 15),
  ('others', 'main', 'Others', 16)
on conflict (system_code) do update set name = excluded.name, sort_order = excluded.sort_order;

insert into public.record_categories (parent_id, system_code, level, name, sort_order)
select parent.id, source.system_code, 'subcategory', source.name, source.sort_order
from (values
  ('food_drinks', 'food_drinks.restaurant_fast_food', 'Restaurant & Fast Food', 1),
  ('food_drinks', 'food_drinks.cafe_bar', 'Café & Bar', 2),
  ('food_drinks', 'food_drinks.groceries', 'Groceries', 3),
  ('shopping', 'shopping.clothes_shoes', 'Clothes & shoes', 1),
  ('shopping', 'shopping.bags', 'Bags', 2),
  ('shopping', 'shopping.accessories', 'Accessories', 3),
  ('shopping', 'shopping.electronics', 'Electronics', 4),
  ('shopping', 'shopping.home_garden', 'Home & Garden', 5),
  ('shopping', 'shopping.health_supplements_vitamins', 'Health (Supplements & Vitamins)', 6),
  ('shopping', 'shopping.jewelry', 'Jewelry', 7),
  ('shopping', 'shopping.gifts', 'Gifts', 8),
  ('shopping', 'shopping.pets_animals', 'Pets & Animals', 9),
  ('housing', 'housing.rent', 'Rent', 1),
  ('housing', 'housing.mortgage', 'Mortgage', 2),
  ('housing', 'housing.utilities', 'Electricity, Gas & any Utilities', 3),
  ('housing', 'housing.maintenance_repair', 'Maintenance & Repair', 4),
  ('housing', 'housing.property_insurance', 'Property Insurance', 5),
  ('housing', 'housing.services', 'Services', 6),
  ('transportation', 'transportation.taxi', 'Taxi', 1),
  ('transportation', 'transportation.train', 'Train', 2),
  ('transportation', 'transportation.bus', 'Bus', 3),
  ('transportation', 'transportation.metro', 'Metro', 4),
  ('transportation', 'transportation.others', 'Others', 5),
  ('travel', 'travel.flight', 'Flight', 1),
  ('travel', 'travel.hotel_accommodation', 'Hotel / Accommodation', 2),
  ('travel', 'travel.visa', 'Visa', 3),
  ('travel', 'travel.tours_activities', 'Tours & Activities', 4),
  ('travel', 'travel.travel_insurance', 'Travel Insurance', 5),
  ('travel', 'travel.travel_transportation', 'Travel Transportation', 6),
  ('vehicle', 'vehicle.insurance', 'Vehicle Insurance', 1),
  ('vehicle', 'vehicle.car_wash', 'Car Wash', 2),
  ('vehicle', 'vehicle.rental', 'Vehicle Rental', 3),
  ('vehicle', 'vehicle.registration_licensing', 'Registration & Licensing', 4),
  ('vehicle', 'vehicle.tolls', 'Tolls', 5),
  ('vehicle', 'vehicle.maintenance', 'Vehicle Maintenance', 6),
  ('vehicle', 'vehicle.parking', 'Parking', 7),
  ('vehicle', 'vehicle.fuel', 'Fuel', 8),
  ('healthcare', 'healthcare.doctor_fees', 'Doctor Fees', 1),
  ('healthcare', 'healthcare.hospital_fees', 'Hospital Fees', 2),
  ('healthcare', 'healthcare.dental', 'Dental', 3),
  ('healthcare', 'healthcare.optical', 'Optical', 4),
  ('healthcare', 'healthcare.pharmacy_medicine', 'Pharmacy & Medicine', 5),
  ('healthcare', 'healthcare.medical_tests', 'Medical Tests', 6),
  ('healthcare', 'healthcare.health_insurance', 'Health Insurance', 7),
  ('education', 'education.school_university', 'School & University', 1),
  ('education', 'education.courses', 'Courses', 2),
  ('education', 'education.books', 'Books', 3),
  ('education', 'education.training', 'Training', 4),
  ('education', 'education.certifications', 'Certifications', 5),
  ('life_entertainment', 'life_entertainment.tailor_laundry', 'Tailor or Laundry', 1),
  ('life_entertainment', 'life_entertainment.tobacco_cigarettes', 'Tobacco & Cigarettes', 2),
  ('life_entertainment', 'life_entertainment.hobbies', 'Hobbies', 3),
  ('life_entertainment', 'life_entertainment.cinema', 'Cinema', 4),
  ('life_entertainment', 'life_entertainment.gym_sport', 'Gym & Sport', 5),
  ('life_entertainment', 'life_entertainment.shaving_wellness', 'Shaving & Wellness', 6),
  ('life_entertainment', 'life_entertainment.games', 'Games', 7),
  ('communication', 'communication.phone_credit', 'Phone Credit', 1),
  ('communication', 'communication.internet', 'Internet', 2),
  ('subscriptions', 'subscriptions.gaming', 'Gaming Subscriptions', 1),
  ('subscriptions', 'subscriptions.apps_software', 'Apps & Software', 2),
  ('subscriptions', 'subscriptions.streaming', 'Streaming', 3),
  ('subscriptions', 'subscriptions.cloud_storage', 'Cloud Storage', 4),
  ('subscriptions', 'subscriptions.memberships', 'Memberships', 5),
  ('family_children', 'family_children.childcare', 'Childcare', 1),
  ('family_children', 'family_children.babysitter_nanny', 'Babysitter / Nanny', 2),
  ('family_children', 'family_children.family_support', 'Family Support', 3),
  ('family_children', 'family_children.allowance', 'Allowance', 4),
  ('family_children', 'family_children.child_expenses', 'Child Expenses', 5),
  ('family_children', 'family_children.parent_support', 'Parent Support', 6),
  ('financial_expenses', 'financial_expenses.charges_fees', 'Charges & Fees', 1),
  ('financial_expenses', 'financial_expenses.fines', 'Fines', 2),
  ('financial_expenses', 'financial_expenses.bank_fees', 'Bank Fees', 3),
  ('financial_expenses', 'financial_expenses.loan_payments', 'Loan Payments', 4),
  ('financial_expenses', 'financial_expenses.interest', 'Interest', 5),
  ('financial_expenses', 'financial_expenses.taxes', 'Taxes', 6),
  ('investments', 'investments.savings', 'Savings', 1),
  ('investments', 'investments.financial_investments', 'Financial Investments', 2),
  ('investments', 'investments.collections', 'Collections', 3),
  ('income', 'income.gifts', 'Gifts', 1),
  ('income', 'income.salary', 'Salary', 2),
  ('income', 'income.business_income', 'Business Income', 3),
  ('income', 'income.freelance', 'Freelance', 4),
  ('income', 'income.bonus', 'Bonus', 5),
  ('income', 'income.refunds', 'Refunds', 6),
  ('income', 'income.rental_income', 'Rental Income', 7),
  ('income', 'income.interest_dividends', 'Interest & Dividends', 8),
  ('income', 'income.incentive_commission', 'Incentive & Commission', 9),
  ('income', 'income.compensation', 'Compensation', 10),
  ('income', 'income.pension', 'Pension', 11),
  ('others', 'others.unknown', 'Unknown', 1),
  ('others', 'others.charity_donations', 'Charity & Donations', 2)
) as source(parent_code, system_code, name, sort_order)
join public.record_categories parent on parent.system_code = source.parent_code
on conflict (system_code) do update set
  parent_id = excluded.parent_id,
  name = excluded.name,
  sort_order = excluded.sort_order;
